intrapred: Fix unused global variable.
Compile error in Linux64/GCC4.8.1:

$HEVC/source/common/IntraPred.cpp:252:15: error: ‘{anonymous}::g_aucIntraFilterType’ defined but not used [-Werror=unused-variable]
 unsigned char g_aucIntraFilterType[][35] = {
               ^