vec: Fix macro paste problem due to invalid tokens.
error: pasting "." and "sad" does not give a valid preprocessing token
error: pasting "sse" and "<" does not give a valid preprocessing token